sudo: required
dist: trusty

services:
  - docker

language: ruby

cache:
  bundler: true

env:
  - GEM=. DB=postgres
  - GEM=decidim-admin DB=postgres
  - GEM=decidim-core DB=postgres
  - GEM=decidim-system DB=postgres

before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"

script:
  - $TRAVIS_BUILD_DIR/run_ci.sh

rvm:
  - 2.3.1
