default: &default
  adapter: postgresql
  encoding: unicode
  database: decidim
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: decidim_development

test:
  <<: *default
  database: decidim_test

production:
  <<: *default
  database: decidim_production
